// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: membership.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MembershipInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                 string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GroupID            string `protobuf:"bytes,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	UserID             string `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GlobalPermissionID string `protobuf:"bytes,4,opt,name=GlobalPermissionID,proto3" json:"GlobalPermissionID,omitempty"`
	UserPermissionID   string `protobuf:"bytes,5,opt,name=UserPermissionID,proto3" json:"UserPermissionID,omitempty"`
	Frozen             bool   `protobuf:"varint,6,opt,name=Frozen,proto3" json:"Frozen,omitempty"`
	Quota              string `protobuf:"bytes,7,opt,name=Quota,proto3" json:"Quota,omitempty"`
}

func (x *MembershipInfo) Reset() {
	*x = MembershipInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MembershipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipInfo) ProtoMessage() {}

func (x *MembershipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipInfo.ProtoReflect.Descriptor instead.
func (*MembershipInfo) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{0}
}

func (x *MembershipInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MembershipInfo) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *MembershipInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MembershipInfo) GetGlobalPermissionID() string {
	if x != nil {
		return x.GlobalPermissionID
	}
	return ""
}

func (x *MembershipInfo) GetUserPermissionID() string {
	if x != nil {
		return x.UserPermissionID
	}
	return ""
}

func (x *MembershipInfo) GetFrozen() bool {
	if x != nil {
		return x.Frozen
	}
	return false
}

func (x *MembershipInfo) GetQuota() string {
	if x != nil {
		return x.Quota
	}
	return ""
}

type MemUserGroupInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GroupID string `protobuf:"bytes,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *MemUserGroupInput) Reset() {
	*x = MemUserGroupInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemUserGroupInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemUserGroupInput) ProtoMessage() {}

func (x *MemUserGroupInput) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemUserGroupInput.ProtoReflect.Descriptor instead.
func (*MemUserGroupInput) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{1}
}

func (x *MemUserGroupInput) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MemUserGroupInput) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type MemberJoinGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                 string  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GroupID            string  `protobuf:"bytes,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	UserID             string  `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GlobalPermissionID string  `protobuf:"bytes,4,opt,name=GlobalPermissionID,proto3" json:"GlobalPermissionID,omitempty"`
	UserPermissionID   string  `protobuf:"bytes,5,opt,name=UserPermissionID,proto3" json:"UserPermissionID,omitempty"`
	Frozen             bool    `protobuf:"varint,6,opt,name=Frozen,proto3" json:"Frozen,omitempty"`
	Quota              *string `protobuf:"bytes,7,opt,name=Quota,proto3,oneof" json:"Quota,omitempty"`
	DisplayName        string  `protobuf:"bytes,8,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Description        string  `protobuf:"bytes,9,opt,name=Description,proto3" json:"Description,omitempty"`
	Extra              string  `protobuf:"bytes,10,opt,name=Extra,proto3" json:"Extra,omitempty"`
	CreatedAt          string  `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt          string  `protobuf:"bytes,12,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *MemberJoinGroup) Reset() {
	*x = MemberJoinGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberJoinGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberJoinGroup) ProtoMessage() {}

func (x *MemberJoinGroup) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberJoinGroup.ProtoReflect.Descriptor instead.
func (*MemberJoinGroup) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{2}
}

func (x *MemberJoinGroup) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MemberJoinGroup) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *MemberJoinGroup) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MemberJoinGroup) GetGlobalPermissionID() string {
	if x != nil {
		return x.GlobalPermissionID
	}
	return ""
}

func (x *MemberJoinGroup) GetUserPermissionID() string {
	if x != nil {
		return x.UserPermissionID
	}
	return ""
}

func (x *MemberJoinGroup) GetFrozen() bool {
	if x != nil {
		return x.Frozen
	}
	return false
}

func (x *MemberJoinGroup) GetQuota() string {
	if x != nil && x.Quota != nil {
		return *x.Quota
	}
	return ""
}

func (x *MemberJoinGroup) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MemberJoinGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MemberJoinGroup) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *MemberJoinGroup) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MemberJoinGroup) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListMembershipByUserInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string       `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Data   *LimitOffset `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *ListMembershipByUserInput) Reset() {
	*x = ListMembershipByUserInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMembershipByUserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipByUserInput) ProtoMessage() {}

func (x *ListMembershipByUserInput) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipByUserInput.ProtoReflect.Descriptor instead.
func (*ListMembershipByUserInput) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{3}
}

func (x *ListMembershipByUserInput) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ListMembershipByUserInput) GetData() *LimitOffset {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListMembershipByUserOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64              `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data  []*MemberJoinGroup `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *ListMembershipByUserOutput) Reset() {
	*x = ListMembershipByUserOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_membership_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMembershipByUserOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipByUserOutput) ProtoMessage() {}

func (x *ListMembershipByUserOutput) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipByUserOutput.ProtoReflect.Descriptor instead.
func (*ListMembershipByUserOutput) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{4}
}

func (x *ListMembershipByUserOutput) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListMembershipByUserOutput) GetData() []*MemberJoinGroup {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_membership_proto protoreflect.FileDescriptor

var file_membership_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2e, 0x0a,
	0x12, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x2a, 0x0a,
	0x10, 0x55, 0x73, 0x65, 0x72, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x55, 0x73, 0x65, 0x72, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x72, 0x6f,
	0x7a, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x46, 0x72, 0x6f, 0x7a, 0x65,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x11, 0x4d, 0x65, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x82,
	0x03, 0x0a, 0x0f, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x12, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x61,
	0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x27, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x5f, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_membership_proto_rawDescOnce sync.Once
	file_membership_proto_rawDescData = file_membership_proto_rawDesc
)

func file_membership_proto_rawDescGZIP() []byte {
	file_membership_proto_rawDescOnce.Do(func() {
		file_membership_proto_rawDescData = protoimpl.X.CompressGZIP(file_membership_proto_rawDescData)
	})
	return file_membership_proto_rawDescData
}

var file_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_membership_proto_goTypes = []interface{}{
	(*MembershipInfo)(nil),             // 0: protos.MembershipInfo
	(*MemUserGroupInput)(nil),          // 1: protos.MemUserGroupInput
	(*MemberJoinGroup)(nil),            // 2: protos.MemberJoinGroup
	(*ListMembershipByUserInput)(nil),  // 3: protos.ListMembershipByUserInput
	(*ListMembershipByUserOutput)(nil), // 4: protos.ListMembershipByUserOutput
	(*LimitOffset)(nil),                // 5: protos.LimitOffset
}
var file_membership_proto_depIdxs = []int32{
	5, // 0: protos.ListMembershipByUserInput.Data:type_name -> protos.LimitOffset
	2, // 1: protos.ListMembershipByUserOutput.Data:type_name -> protos.MemberJoinGroup
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_membership_proto_init() }
func file_membership_proto_init() {
	if File_membership_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_membership_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MembershipInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemUserGroupInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberJoinGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMembershipByUserInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_membership_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMembershipByUserOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_membership_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_membership_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_membership_proto_goTypes,
		DependencyIndexes: file_membership_proto_depIdxs,
		MessageInfos:      file_membership_proto_msgTypes,
	}.Build()
	File_membership_proto = out.File
	file_membership_proto_rawDesc = nil
	file_membership_proto_goTypes = nil
	file_membership_proto_depIdxs = nil
}
