// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: services.proto

package protos

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_services_proto protoreflect.FileDescriptor

var file_services_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x10, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xa7,
	0x03, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x43, 0x55, 0x52, 0x44, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x2d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x44, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0x00, 0x12, 0x34, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x3b, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x32, 0xf0, 0x02, 0x0a, 0x13, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x55, 0x52, 0x44, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x12, 0x3a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x44, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x00, 0x12, 0x3c, 0x0a,
	0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x32, 0xca, 0x02, 0x0a, 0x18,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x43, 0x55, 0x52, 0x44, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x47,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x6d, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x15, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_services_proto_goTypes = []interface{}{
	(*UserInfo)(nil),                   // 0: protos.UserInfo
	(*UserID)(nil),                     // 1: protos.UserID
	(*GroupID)(nil),                    // 2: protos.GroupID
	(*LimitOffset)(nil),                // 3: protos.LimitOffset
	(*UpdateInput)(nil),                // 4: protos.UpdateInput
	(*empty.Empty)(nil),                // 5: google.protobuf.Empty
	(*GroupInfo)(nil),                  // 6: protos.GroupInfo
	(*MembershipInfo)(nil),             // 7: protos.MembershipInfo
	(*MemUserGroupInput)(nil),          // 8: protos.MemUserGroupInput
	(*ListMembershipByUserInput)(nil),  // 9: protos.ListMembershipByUserInput
	(*GetUserByGroupOutput)(nil),       // 10: protos.GetUserByGroupOutput
	(*UserInfos)(nil),                  // 11: protos.UserInfos
	(*CountOutput)(nil),                // 12: protos.CountOutput
	(*GroupInfos)(nil),                 // 13: protos.GroupInfos
	(*ListMembershipByUserOutput)(nil), // 14: protos.ListMembershipByUserOutput
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: protos.UserCURDController.CreateUser:input_type -> protos.UserInfo
	1,  // 1: protos.UserCURDController.GetUser:input_type -> protos.UserID
	2,  // 2: protos.UserCURDController.GetUserByGroup:input_type -> protos.GroupID
	3,  // 3: protos.UserCURDController.ListUser:input_type -> protos.LimitOffset
	1,  // 4: protos.UserCURDController.DeleteUser:input_type -> protos.UserID
	4,  // 5: protos.UserCURDController.UpdateUser:input_type -> protos.UpdateInput
	5,  // 6: protos.UserCURDController.CountUser:input_type -> google.protobuf.Empty
	6,  // 7: protos.GroupCURDController.CreateGroup:input_type -> protos.GroupInfo
	2,  // 8: protos.GroupCURDController.DeleteGroup:input_type -> protos.GroupID
	2,  // 9: protos.GroupCURDController.GetGroup:input_type -> protos.GroupID
	5,  // 10: protos.GroupCURDController.CountGroup:input_type -> google.protobuf.Empty
	3,  // 11: protos.GroupCURDController.ListGroup:input_type -> protos.LimitOffset
	4,  // 12: protos.GroupCURDController.UpdateGroup:input_type -> protos.UpdateInput
	7,  // 13: protos.MembershipCURDController.CreateMembership:input_type -> protos.MembershipInfo
	8,  // 14: protos.MembershipCURDController.DeleteMembership:input_type -> protos.MemUserGroupInput
	1,  // 15: protos.MembershipCURDController.CountMembershipByUser:input_type -> protos.UserID
	9,  // 16: protos.MembershipCURDController.ListMembershipByUser:input_type -> protos.ListMembershipByUserInput
	5,  // 17: protos.UserCURDController.CreateUser:output_type -> google.protobuf.Empty
	0,  // 18: protos.UserCURDController.GetUser:output_type -> protos.UserInfo
	10, // 19: protos.UserCURDController.GetUserByGroup:output_type -> protos.GetUserByGroupOutput
	11, // 20: protos.UserCURDController.ListUser:output_type -> protos.UserInfos
	5,  // 21: protos.UserCURDController.DeleteUser:output_type -> google.protobuf.Empty
	5,  // 22: protos.UserCURDController.UpdateUser:output_type -> google.protobuf.Empty
	12, // 23: protos.UserCURDController.CountUser:output_type -> protos.CountOutput
	5,  // 24: protos.GroupCURDController.CreateGroup:output_type -> google.protobuf.Empty
	5,  // 25: protos.GroupCURDController.DeleteGroup:output_type -> google.protobuf.Empty
	6,  // 26: protos.GroupCURDController.GetGroup:output_type -> protos.GroupInfo
	12, // 27: protos.GroupCURDController.CountGroup:output_type -> protos.CountOutput
	13, // 28: protos.GroupCURDController.ListGroup:output_type -> protos.GroupInfos
	5,  // 29: protos.GroupCURDController.UpdateGroup:output_type -> google.protobuf.Empty
	5,  // 30: protos.MembershipCURDController.CreateMembership:output_type -> google.protobuf.Empty
	5,  // 31: protos.MembershipCURDController.DeleteMembership:output_type -> google.protobuf.Empty
	12, // 32: protos.MembershipCURDController.CountMembershipByUser:output_type -> protos.CountOutput
	14, // 33: protos.MembershipCURDController.ListMembershipByUser:output_type -> protos.ListMembershipByUserOutput
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	file_user_proto_init()
	file_group_proto_init()
	file_membership_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
	}.Build()
	File_services_proto = out.File
	file_services_proto_rawDesc = nil
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserCURDControllerClient is the client API for UserCURDController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserCURDControllerClient interface {
	CreateUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserInfo, error)
	GetUserByGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*GetUserByGroupOutput, error)
	ListUser(ctx context.Context, in *LimitOffset, opts ...grpc.CallOption) (*UserInfos, error)
	DeleteUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateUser(ctx context.Context, in *UpdateInput, opts ...grpc.CallOption) (*empty.Empty, error)
	CountUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountOutput, error)
}

type userCURDControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCURDControllerClient(cc grpc.ClientConnInterface) UserCURDControllerClient {
	return &userCURDControllerClient{cc}
}

func (c *userCURDControllerClient) CreateUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.UserCURDController/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDControllerClient) GetUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/protos.UserCURDController/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDControllerClient) GetUserByGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*GetUserByGroupOutput, error) {
	out := new(GetUserByGroupOutput)
	err := c.cc.Invoke(ctx, "/protos.UserCURDController/GetUserByGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDControllerClient) ListUser(ctx context.Context, in *LimitOffset, opts ...grpc.CallOption) (*UserInfos, error) {
	out := new(UserInfos)
	err := c.cc.Invoke(ctx, "/protos.UserCURDController/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDControllerClient) DeleteUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.UserCURDController/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDControllerClient) UpdateUser(ctx context.Context, in *UpdateInput, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.UserCURDController/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDControllerClient) CountUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountOutput, error) {
	out := new(CountOutput)
	err := c.cc.Invoke(ctx, "/protos.UserCURDController/CountUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCURDControllerServer is the server API for UserCURDController service.
type UserCURDControllerServer interface {
	CreateUser(context.Context, *UserInfo) (*empty.Empty, error)
	GetUser(context.Context, *UserID) (*UserInfo, error)
	GetUserByGroup(context.Context, *GroupID) (*GetUserByGroupOutput, error)
	ListUser(context.Context, *LimitOffset) (*UserInfos, error)
	DeleteUser(context.Context, *UserID) (*empty.Empty, error)
	UpdateUser(context.Context, *UpdateInput) (*empty.Empty, error)
	CountUser(context.Context, *empty.Empty) (*CountOutput, error)
}

// UnimplementedUserCURDControllerServer can be embedded to have forward compatible implementations.
type UnimplementedUserCURDControllerServer struct {
}

func (*UnimplementedUserCURDControllerServer) CreateUser(context.Context, *UserInfo) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserCURDControllerServer) GetUser(context.Context, *UserID) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserCURDControllerServer) GetUserByGroup(context.Context, *GroupID) (*GetUserByGroupOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByGroup not implemented")
}
func (*UnimplementedUserCURDControllerServer) ListUser(context.Context, *LimitOffset) (*UserInfos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (*UnimplementedUserCURDControllerServer) DeleteUser(context.Context, *UserID) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserCURDControllerServer) UpdateUser(context.Context, *UpdateInput) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserCURDControllerServer) CountUser(context.Context, *empty.Empty) (*CountOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountUser not implemented")
}

func RegisterUserCURDControllerServer(s *grpc.Server, srv UserCURDControllerServer) {
	s.RegisterService(&_UserCURDController_serviceDesc, srv)
}

func _UserCURDController_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDControllerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserCURDController/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDControllerServer).CreateUser(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURDController_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDControllerServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserCURDController/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDControllerServer).GetUser(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURDController_GetUserByGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDControllerServer).GetUserByGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserCURDController/GetUserByGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDControllerServer).GetUserByGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURDController_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LimitOffset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDControllerServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserCURDController/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDControllerServer).ListUser(ctx, req.(*LimitOffset))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURDController_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDControllerServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserCURDController/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDControllerServer).DeleteUser(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURDController_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDControllerServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserCURDController/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDControllerServer).UpdateUser(ctx, req.(*UpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURDController_CountUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDControllerServer).CountUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserCURDController/CountUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDControllerServer).CountUser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserCURDController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UserCURDController",
	HandlerType: (*UserCURDControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserCURDController_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserCURDController_GetUser_Handler,
		},
		{
			MethodName: "GetUserByGroup",
			Handler:    _UserCURDController_GetUserByGroup_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _UserCURDController_ListUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserCURDController_DeleteUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserCURDController_UpdateUser_Handler,
		},
		{
			MethodName: "CountUser",
			Handler:    _UserCURDController_CountUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}

// GroupCURDControllerClient is the client API for GroupCURDController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupCURDControllerClient interface {
	CreateGroup(ctx context.Context, in *GroupInfo, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*empty.Empty, error)
	GetGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*GroupInfo, error)
	CountGroup(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountOutput, error)
	ListGroup(ctx context.Context, in *LimitOffset, opts ...grpc.CallOption) (*GroupInfos, error)
	UpdateGroup(ctx context.Context, in *UpdateInput, opts ...grpc.CallOption) (*empty.Empty, error)
}

type groupCURDControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupCURDControllerClient(cc grpc.ClientConnInterface) GroupCURDControllerClient {
	return &groupCURDControllerClient{cc}
}

func (c *groupCURDControllerClient) CreateGroup(ctx context.Context, in *GroupInfo, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.GroupCURDController/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupCURDControllerClient) DeleteGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.GroupCURDController/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupCURDControllerClient) GetGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*GroupInfo, error) {
	out := new(GroupInfo)
	err := c.cc.Invoke(ctx, "/protos.GroupCURDController/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupCURDControllerClient) CountGroup(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountOutput, error) {
	out := new(CountOutput)
	err := c.cc.Invoke(ctx, "/protos.GroupCURDController/CountGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupCURDControllerClient) ListGroup(ctx context.Context, in *LimitOffset, opts ...grpc.CallOption) (*GroupInfos, error) {
	out := new(GroupInfos)
	err := c.cc.Invoke(ctx, "/protos.GroupCURDController/ListGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupCURDControllerClient) UpdateGroup(ctx context.Context, in *UpdateInput, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.GroupCURDController/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupCURDControllerServer is the server API for GroupCURDController service.
type GroupCURDControllerServer interface {
	CreateGroup(context.Context, *GroupInfo) (*empty.Empty, error)
	DeleteGroup(context.Context, *GroupID) (*empty.Empty, error)
	GetGroup(context.Context, *GroupID) (*GroupInfo, error)
	CountGroup(context.Context, *empty.Empty) (*CountOutput, error)
	ListGroup(context.Context, *LimitOffset) (*GroupInfos, error)
	UpdateGroup(context.Context, *UpdateInput) (*empty.Empty, error)
}

// UnimplementedGroupCURDControllerServer can be embedded to have forward compatible implementations.
type UnimplementedGroupCURDControllerServer struct {
}

func (*UnimplementedGroupCURDControllerServer) CreateGroup(context.Context, *GroupInfo) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedGroupCURDControllerServer) DeleteGroup(context.Context, *GroupID) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (*UnimplementedGroupCURDControllerServer) GetGroup(context.Context, *GroupID) (*GroupInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (*UnimplementedGroupCURDControllerServer) CountGroup(context.Context, *empty.Empty) (*CountOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountGroup not implemented")
}
func (*UnimplementedGroupCURDControllerServer) ListGroup(context.Context, *LimitOffset) (*GroupInfos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroup not implemented")
}
func (*UnimplementedGroupCURDControllerServer) UpdateGroup(context.Context, *UpdateInput) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}

func RegisterGroupCURDControllerServer(s *grpc.Server, srv GroupCURDControllerServer) {
	s.RegisterService(&_GroupCURDController_serviceDesc, srv)
}

func _GroupCURDController_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCURDControllerServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GroupCURDController/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCURDControllerServer).CreateGroup(ctx, req.(*GroupInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupCURDController_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCURDControllerServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GroupCURDController/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCURDControllerServer).DeleteGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupCURDController_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCURDControllerServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GroupCURDController/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCURDControllerServer).GetGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupCURDController_CountGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCURDControllerServer).CountGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GroupCURDController/CountGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCURDControllerServer).CountGroup(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupCURDController_ListGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LimitOffset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCURDControllerServer).ListGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GroupCURDController/ListGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCURDControllerServer).ListGroup(ctx, req.(*LimitOffset))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupCURDController_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCURDControllerServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GroupCURDController/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCURDControllerServer).UpdateGroup(ctx, req.(*UpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupCURDController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.GroupCURDController",
	HandlerType: (*GroupCURDControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _GroupCURDController_CreateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _GroupCURDController_DeleteGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _GroupCURDController_GetGroup_Handler,
		},
		{
			MethodName: "CountGroup",
			Handler:    _GroupCURDController_CountGroup_Handler,
		},
		{
			MethodName: "ListGroup",
			Handler:    _GroupCURDController_ListGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _GroupCURDController_UpdateGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}

// MembershipCURDControllerClient is the client API for MembershipCURDController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MembershipCURDControllerClient interface {
	CreateMembership(ctx context.Context, in *MembershipInfo, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteMembership(ctx context.Context, in *MemUserGroupInput, opts ...grpc.CallOption) (*empty.Empty, error)
	CountMembershipByUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*CountOutput, error)
	ListMembershipByUser(ctx context.Context, in *ListMembershipByUserInput, opts ...grpc.CallOption) (*ListMembershipByUserOutput, error)
}

type membershipCURDControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipCURDControllerClient(cc grpc.ClientConnInterface) MembershipCURDControllerClient {
	return &membershipCURDControllerClient{cc}
}

func (c *membershipCURDControllerClient) CreateMembership(ctx context.Context, in *MembershipInfo, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.MembershipCURDController/CreateMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCURDControllerClient) DeleteMembership(ctx context.Context, in *MemUserGroupInput, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protos.MembershipCURDController/DeleteMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCURDControllerClient) CountMembershipByUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*CountOutput, error) {
	out := new(CountOutput)
	err := c.cc.Invoke(ctx, "/protos.MembershipCURDController/CountMembershipByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCURDControllerClient) ListMembershipByUser(ctx context.Context, in *ListMembershipByUserInput, opts ...grpc.CallOption) (*ListMembershipByUserOutput, error) {
	out := new(ListMembershipByUserOutput)
	err := c.cc.Invoke(ctx, "/protos.MembershipCURDController/ListMembershipByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipCURDControllerServer is the server API for MembershipCURDController service.
type MembershipCURDControllerServer interface {
	CreateMembership(context.Context, *MembershipInfo) (*empty.Empty, error)
	DeleteMembership(context.Context, *MemUserGroupInput) (*empty.Empty, error)
	CountMembershipByUser(context.Context, *UserID) (*CountOutput, error)
	ListMembershipByUser(context.Context, *ListMembershipByUserInput) (*ListMembershipByUserOutput, error)
}

// UnimplementedMembershipCURDControllerServer can be embedded to have forward compatible implementations.
type UnimplementedMembershipCURDControllerServer struct {
}

func (*UnimplementedMembershipCURDControllerServer) CreateMembership(context.Context, *MembershipInfo) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMembership not implemented")
}
func (*UnimplementedMembershipCURDControllerServer) DeleteMembership(context.Context, *MemUserGroupInput) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMembership not implemented")
}
func (*UnimplementedMembershipCURDControllerServer) CountMembershipByUser(context.Context, *UserID) (*CountOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountMembershipByUser not implemented")
}
func (*UnimplementedMembershipCURDControllerServer) ListMembershipByUser(context.Context, *ListMembershipByUserInput) (*ListMembershipByUserOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembershipByUser not implemented")
}

func RegisterMembershipCURDControllerServer(s *grpc.Server, srv MembershipCURDControllerServer) {
	s.RegisterService(&_MembershipCURDController_serviceDesc, srv)
}

func _MembershipCURDController_CreateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembershipInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCURDControllerServer).CreateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.MembershipCURDController/CreateMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCURDControllerServer).CreateMembership(ctx, req.(*MembershipInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCURDController_DeleteMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemUserGroupInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCURDControllerServer).DeleteMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.MembershipCURDController/DeleteMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCURDControllerServer).DeleteMembership(ctx, req.(*MemUserGroupInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCURDController_CountMembershipByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCURDControllerServer).CountMembershipByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.MembershipCURDController/CountMembershipByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCURDControllerServer).CountMembershipByUser(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCURDController_ListMembershipByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembershipByUserInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCURDControllerServer).ListMembershipByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.MembershipCURDController/ListMembershipByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCURDControllerServer).ListMembershipByUser(ctx, req.(*ListMembershipByUserInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _MembershipCURDController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.MembershipCURDController",
	HandlerType: (*MembershipCURDControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMembership",
			Handler:    _MembershipCURDController_CreateMembership_Handler,
		},
		{
			MethodName: "DeleteMembership",
			Handler:    _MembershipCURDController_DeleteMembership_Handler,
		},
		{
			MethodName: "CountMembershipByUser",
			Handler:    _MembershipCURDController_CountMembershipByUser_Handler,
		},
		{
			MethodName: "ListMembershipByUser",
			Handler:    _MembershipCURDController_ListMembershipByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
